



resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}





service:
  type: ClusterIP
  port: 80



ingress:
  name: ingress
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  domain: "example.com"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


mongodbReplicaset:
  name: mongodb-replicaset


elasticsearch:
  name: elasticsearch

  containers:
    resources:
      requests:
        cpu: .10
        memory: 2560Mi
      limits:
        cpu: .75
        memory: 3072Mi

  volumeClaimTemplates:
    resources:
      requests:
        storage: 100Gi


graylog:
  passwordSecret: {}

  web:
    service:
      externalPort: 80
      internalPort: 9000


  image:
    tag: 2.4.4-1

  master:
    name: master
  slave:
    name: slave
